# Generated by Django 3.1.2 on 2020-11-22 01:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SexModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_id', models.CharField(max_length=1, unique='true')),
                ('value', models.CharField(max_length=10)),
                ('create_dt', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '性別マスタ',
                'verbose_name_plural': '性別マスタ',
            },
        ),
        migrations.CreateModel(
            name='KimetsuCharactorModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('characteristic', models.CharField(max_length=300)),
                ('create_dt', models.DateTimeField(default=datetime.datetime.now)),
                ('sex_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='loginapp.sexmodel')),
            ],
            options={
                'verbose_name': '鬼滅の刃キャラクター',
                'verbose_name_plural': '鬼滅の刃キャラクター',
                'unique_together': {('name', 'sex_id')},
            },
        ),
    ]
