# Generated by Django 3.1.3 on 2020-11-29 00:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kimetsucharactormodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='kimetsucharactormodel',
            name='characteristic',
            field=models.CharField(max_length=300, verbose_name='特徴'),
        ),
        migrations.AlterField(
            model_name='kimetsucharactormodel',
            name='create_dt',
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='kimetsucharactormodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='kimetsucharactormodel',
            name='sex_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='loginapp.sexmodel', verbose_name='性別ID'),
        ),
        migrations.AlterField(
            model_name='sexmodel',
            name='value',
            field=models.CharField(max_length=10, verbose_name='性別ID'),
        ),
    ]
